# Generated by Django 4.2.6 on 2023-10-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner_personagem_LIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('tipo', models.CharField(choices=[('1', 'Destruição'), ('2', 'Caça'), ('3', 'Abundância'), ('4', 'Preservação'), ('5', 'Inexistência'), ('6', 'Harmonia'), ('7', 'Erudição')], max_length=1)),
                ('rerun', models.IntegerField(default=0)),
                ('foto', models.FileField(blank=True, null=True, upload_to='foto')),
            ],
        ),
    ]
