# Generated by Django 4.2.6 on 2023-10-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_banner_personagem_lim_rerun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_personagem_comum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_c', models.CharField(max_length=50)),
                ('tipo_c', models.IntegerField(choices=[(1, 'Destruição'), (2, 'Caça'), (3, 'Abundância'), (4, 'Preservação'), (5, 'Inexistência'), (6, 'Harmonia'), (7, 'Erudição')])),
                ('foto_c', models.FileField(blank=True, null=True, upload_to='foto')),
            ],
        ),
    ]
