# Generated by Django 4.2.6 on 2023-10-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_banner_personagem_lim_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('caminho', models.IntegerField(blank=True, choices=[(1, 'Destruição'), (2, 'Caça'), (3, 'Abundância'), (4, 'Preservação'), (5, 'Inexistência'), (6, 'Harmonia'), (7, 'Erudição')], null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='foto')),
                ('tipo', models.BooleanField(default=False)),
            ],
        ),
    ]
