# Generated by Django 4.2.6 on 2023-10-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiro', '0004_tiro_b_personagem_remove_tiro_limitado_nome_and_more'),
        ('cadastro', '0007_banner_personagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='banner_personagem_comum',
        ),
        migrations.DeleteModel(
            name='banner_personagem_LIM',
        ),
    ]
