# Generated by Django 4.2.6 on 2023-10-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_delete_banner_personagem_comum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_a', models.CharField(max_length=50)),
                ('data_inicio_a', models.DateField(blank=True, null=True)),
                ('data_final_a', models.DateField(blank=True, null=True)),
                ('foto_a', models.FileField(upload_to='foto')),
                ('tipo_a', models.BooleanField(default=False)),
            ],
        ),
    ]
