# Generated by Django 4.2.6 on 2024-07-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_banner_arma'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_personagem',
            name='foto_m',
            field=models.FileField(blank=True, null=True, upload_to='mini-foto'),
        ),
    ]
