# Generated by Django 4.2.6 on 2024-07-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_banner_personagem_foto_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerArmaAntigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_a', models.CharField(max_length=50)),
                ('data_inicio_a', models.DateField(blank=True, null=True)),
                ('data_final_a', models.DateField(blank=True, null=True)),
                ('foto_a', models.FileField(upload_to='foto')),
                ('tipo_a', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'banner_arma',
            },
        ),
        migrations.CreateModel(
            name='BannerPersonagemAntigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('caminho', models.IntegerField(blank=True, choices=[(1, 'Destruição'), (2, 'Caça'), (3, 'Abundância'), (4, 'Preservação'), (5, 'Inexistência'), (6, 'Harmonia'), (7, 'Erudição')], null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='foto')),
                ('foto_m', models.FileField(blank=True, null=True, upload_to='mini-foto')),
                ('tipo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'banner_personagem',
            },
        ),
    ]
