# Generated by Django 4.2.6 on 2024-07-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_bannerarmaantigo_bannerpersonagemantigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.FileField(upload_to='foto')),
                ('tipo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BannerPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('caminho', models.IntegerField(choices=[(1, 'Destruição'), (2, 'Caça'), (3, 'Abundância'), (4, 'Preservação'), (5, 'Inexistência'), (6, 'Harmonia'), (7, 'Erudição')])),
                ('foto', models.FileField(upload_to='foto')),
                ('foto_m', models.FileField(upload_to='mini-foto')),
                ('tipo', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='BannerArmaAntigo',
        ),
        migrations.DeleteModel(
            name='BannerPersonagemAntigo',
        ),
    ]
