# Generated by Django 4.2.6 on 2024-07-21 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_delete_bannerarma_delete_bannerpersonagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner_arma',
            name='data_final_a',
        ),
        migrations.RemoveField(
            model_name='banner_arma',
            name='data_inicio_a',
        ),
        migrations.RemoveField(
            model_name='banner_personagem',
            name='data_final',
        ),
        migrations.RemoveField(
            model_name='banner_personagem',
            name='data_inicio',
        ),
    ]
