# Generated by Django 4.2.6 on 2023-10-19 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0003_banner_personagem_comum'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiro_limitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_T', models.IntegerField()),
                ('data_adc', models.DateField()),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.banner_personagem_lim')),
                ('nome_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.banner_personagem_comum')),
            ],
        ),
        migrations.CreateModel(
            name='tiro_comum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_T', models.IntegerField()),
                ('data_adc', models.DateField()),
                ('nome_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.banner_personagem_comum')),
            ],
        ),
    ]
