# Generated by Django 4.2.6 on 2023-10-20 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_banner_personagem_lim_tipo'),
        ('tiro', '0002_rename_data_adc_tiro_limitado_data_adc_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiro_limitado',
            name='nome_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.banner_personagem_comum'),
        ),
    ]
