# Generated by Django 4.2.6 on 2023-10-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_banner_personagem'),
        ('tiro', '0003_alter_tiro_limitado_nome_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiro_b_personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_t', models.IntegerField()),
                ('data_adc', models.DateField()),
                ('tipo_t', models.BooleanField(default=False)),
                ('nome_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.banner_personagem')),
            ],
        ),
        migrations.RemoveField(
            model_name='tiro_limitado',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='tiro_limitado',
            name='nome_c',
        ),
        migrations.DeleteModel(
            name='tiro_comum',
        ),
        migrations.DeleteModel(
            name='tiro_limitado',
        ),
    ]
