# Generated by Django 4.2.6 on 2023-10-26 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_banner_arma'),
        ('tiro', '0004_tiro_b_personagem_remove_tiro_limitado_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiro_b_arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ta', models.IntegerField()),
                ('data_tadc', models.DateField()),
                ('tipo_ta', models.BooleanField(default=False)),
                ('nome_ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.banner_arma')),
            ],
        ),
    ]
