# Generated by Django 4.2.6 on 2024-07-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_bannerarma_bannerpersonagem_delete_bannerarmaantigo_and_more'),
        ('tiro', '0005_tiro_b_arma'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaBannerArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('numero_ocorrencia', models.IntegerField()),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='cadastro.bannerarma')),
            ],
        ),
        migrations.CreateModel(
            name='OcorrenciaBannerPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('numero_ocorrencia', models.IntegerField()),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='cadastro.bannerpersonagem')),
            ],
        ),
        migrations.CreateModel(
            name='TiroPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tiros', models.IntegerField()),
                ('data', models.DateField()),
                ('tipo', models.BooleanField(default=False)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiro.ocorrenciabannerpersonagem')),
            ],
        ),
        migrations.CreateModel(
            name='TiroArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tiros', models.IntegerField()),
                ('data', models.DateField()),
                ('tipo', models.BooleanField(default=False)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiro.ocorrenciabannerarma')),
            ],
        ),
    ]
