# Generated by Django 4.2.6 on 2024-07-21 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiro', '0007_remove_ocorrenciabannerpersonagem_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiro_b_arma',
            name='nome_ta',
        ),
        migrations.RemoveField(
            model_name='tiro_b_personagem',
            name='nome_p',
        ),
    ]
